---
abstract: 'debug unicode strings'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Debug
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Devel::Unicode:
    file: lib/Devel/Unicode.pm
    version: 0.002
  PerlIO::via::UnicodeDebug:
    file: lib/PerlIO/via/UnicodeDebug.pm
    version: 0.002
  Unicode::Debug:
    file: lib/Unicode/Debug.pm
    version: 0.002
requires:
  perl: 5.008001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Unicode-Debug/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Unicode-Debug
  homepage: https://metacpan.org/release/Unicode-Debug
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-unicode-debug
version: 0.002
